# Generated by Django 3.1.1 on 2020-10-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_order_is_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='list_product',
            field=models.BooleanField(default=True),
        ),
    ]
