# Generated by Django 3.1.1 on 2020-10-11 09:14

from django.db import migrations, models
import ecom.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_product_list_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default=ecom.models.default_product_name, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=ecom.models.default_product_price),
        ),
    ]
