# Generated by Django 3.1.1 on 2020-10-12 09:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_auto_20201011_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='productincart',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 12, 9, 47, 7, 436473, tzinfo=utc)),
        ),
    ]
