# Generated by Django 3.1.1 on 2020-10-12 09:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_productincart_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productincart',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 12, 9, 48, 49, 205103, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productincart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
