# Generated by Django 3.1.1 on 2020-10-12 09:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_auto_20201012_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productincart',
            name='order_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 12, 9, 54, 58, 129856, tzinfo=utc)),
        ),
    ]
