# Generated by Django 3.1.1 on 2020-10-12 10:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_auto_20201012_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 12, 10, 17, 58, 912820, tzinfo=utc)),
        ),
    ]
