# Generated by Django 3.1.1 on 2020-10-14 17:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_auto_20201014_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 14, 17, 4, 48, 926768, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('B', 'Bread'), ('E', 'Egg'), ('M', 'Milk'), ('C', 'Chips')], max_length=1),
        ),
    ]
