# Generated by Django 3.1.1 on 2020-10-14 17:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import ecom.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_auto_20201014_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=ecom.models.default_cat, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 14, 17, 11, 16, 742621, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='ecom.Category'),
        ),
    ]
