# Generated by Django 3.1.1 on 2020-10-14 17:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import ecom.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_auto_20201014_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default=ecom.models.default_cat, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 14, 17, 17, 19, 831427, tzinfo=utc)),
        ),
    ]
