# Generated by Django 3.1.1 on 2020-11-03 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import ecom.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_auto_20201014_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default=ecom.models.default_cat, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 17, 8, 46, 437986, tzinfo=utc)),
        ),
    ]
