# Generated by Django 3.1.1 on 2020-11-03 18:08

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecom', '0013_auto_20201103_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 8, 32, 205839, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Hostel', max_length=20)),
                ('address_1', models.CharField(default='Address', max_length=200)),
                ('address_2', models.CharField(blank=True, default='Address', max_length=200, null=True)),
                ('mobile_number', models.IntegerField(default='1234567890', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10)])),
                ('zipcode', models.IntegerField(default='400035', validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(6)])),
                ('city', models.CharField(default='mumbai', max_length=20)),
                ('save', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
