# Generated by Django 3.1.1 on 2020-11-03 18:14

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0016_auto_20201103_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='mobile_number',
            field=models.IntegerField(default='1234567890', validators=[django.core.validators.MinValueValidator(999999999), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.IntegerField(default='400035', validators=[django.core.validators.MinValueValidator(99999), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 14, 46, 540979, tzinfo=utc)),
        ),
    ]
