# Generated by Django 3.1.1 on 2020-11-03 18:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0017_auto_20201103_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='save',
            new_name='is_save',
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 16, 10, 645038, tzinfo=utc)),
        ),
    ]
