# Generated by Django 3.1.1 on 2020-11-04 18:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0018_auto_20201103_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('P', 'PayTm'), ('S', 'Stripe'), ('N', 'None')], default='N', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 4, 18, 10, 22, 818847, tzinfo=utc)),
        ),
    ]
