# Generated by Django 3.1.1 on 2020-11-08 13:37

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0024_auto_20201108_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='address_1',
            field=models.CharField(default='Address', max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='address_2',
            field=models.CharField(blank=True, default='Address', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='city',
            field=models.CharField(default='mumbai', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mobile_number',
            field=models.IntegerField(default='1234567890', validators=[django.core.validators.MinValueValidator(999999999), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(default='Hostel', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='zipcode',
            field=models.IntegerField(default='400035', validators=[django.core.validators.MinValueValidator(99999), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 13, 37, 14, 661144, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 13, 37, 14, 662261, tzinfo=utc)),
        ),
    ]
