# Generated by Django 3.1.1 on 2020-11-08 13:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0025_auto_20201108_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='address_1',
            new_name='address_address_1',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='address_2',
            new_name='address_address_2',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='city',
            new_name='address_city',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='mobile_number',
            new_name='address_mobile_number',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='name',
            new_name='address_name',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='zipcode',
            new_name='address_zipcode',
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 13, 42, 57, 394383, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 13, 42, 57, 395507, tzinfo=utc)),
        ),
    ]
