# Generated by Django 3.1.1 on 2020-11-08 13:54

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0027_auto_20201108_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='mobile_number',
            field=models.IntegerField(blank=True, default='1234567890', null=True, validators=[django.core.validators.MinValueValidator(999999999), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 13, 54, 4, 21307, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 13, 54, 4, 22424, tzinfo=utc)),
        ),
    ]
