# Generated by Django 3.1.1 on 2020-12-14 13:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0030_auto_20201109_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='ip',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 13, 2, 28, 545652, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 13, 2, 28, 547215, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 13, 2, 28, 548334, tzinfo=utc)),
        ),
    ]
