# Generated by Django 3.1.1 on 2020-12-14 17:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0033_auto_20201214_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(to='ecom.Image'),
        ),
        migrations.AlterField(
            model_name='ip',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 17, 7, 9, 771102, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 17, 7, 9, 772535, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 17, 7, 9, 773879, tzinfo=utc)),
        ),
    ]
