# Generated by Django 3.1.2 on 2021-04-09 04:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0035_auto_20201214_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 4, 17, 14, 239185, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 4, 17, 14, 240690, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 4, 17, 14, 241953, tzinfo=utc)),
        ),
    ]
